### ISSUE TITLE
`addr::remote()` is `None` for TLS connections

### ISSUE THREAD

**Issue by benruijl** [seanmonstar/warp#559] opened 2020-05-02 09:41 UTC
When I start a server using `warp::serve(routes).tls()` the filter `warp::addr::remote()` returns `None`. If I disable TLS, I do get the remote address.

How can I get the IP address of a client when using `tls`?

**Comment by abreis** [comment] 2020-06-16 22:15
I tried to reproduce this but it seems to be working on my end. The code:
```rust
#[tokio::main]
async fn main() {
    use warp::Filter;
    let routes = warp::addr::remote().map(|addr| format!("Hello {:?}!", addr));
    warp::serve(routes)
        .tls()
        .cert_path("examples/tls/cert.pem")
        .key_path("examples/tls/key.rsa")
        .run(([127, 0, 0, 1], 3030))
        .await;
}
```
gives:
```sh
$ curl --insecure https://127.0.0.1:3030/hello
Hello Some(V4(127.0.0.1:58188))!
```

Can you show more of the code you're running?

**Comment by abreis** [comment] 2020-06-16 22:18
Actually: it's a duplicate of #514. Should be fixed in v0.2.3.

**Comment by seanmonstar** [comment] 2020-06-16 22:21
Thanks for noticing!

**Closed** 2020-06-16 22:21 UTC
