### ISSUE TITLE
Error message with rejection

### ISSUE THREAD

**Issue by kiljacken** [seanmonstar/warp#37] opened 2018-08-08 10:22 UTC
It would be nice if the rejections allowed passing an error message, so the end user of an API has a chance of knowing what they did wrong (for example on bad request).

**Comment by hjr3** [comment] 2018-08-08 14:28
I have been playing around with warp and have run into this as well. The `warp::Reply` trait allows [a number](https://github.com/seanmonstar/warp/blob/45f8535662afde031c04d0a96c8d490c72212495/src/reply.rs#L11) of different ways to create a reply. This allows for simple use cases (using only a string or number) and complex use cases that want to build up complex responses using `http::Response`.

The `warp::Rejection` type is a dead end in that it only accepts a reason code. There are use cases where I want to return a body along with the reason code and even other use cases where I want to set a `Content-Type` header as well.

I think `warp::Rejection` should to allow for an `http::Response` or `ReplySealed` should to be implemented for `Result<impl warp::Reply, impl warp::Reply>`.

**Comment by kamalmarhubi** [comment] 2018-08-11 02:29
I believe the intent with `Rejection` is to be a very small error type that covers the most common errors. In the hypothetical 1.0 release, I think that the [`Reject` trait](https://github.com/seanmonstar/warp/blob/283a5463d7548a24afc69bf2f2521148aacb7061/src/reject.rs#L174-L177) would be unsealed, and you'd have your custom error implement that.

**Comment by dmexe** [comment] 2018-08-15 14:58
Proposal: Error reform
======================

Current State
-------------

`Reject` holds only a status `Reason: u8` which can be composed with another rejection to determine final `Filter` result. (as I understood after digging a code)

So `Reject` usable for flow control during `Filter`execution and lacks an error description which critical for debugging and ops. In many cases, an error cause just lost (for example https://github.com/seanmonstar/warp/blob/master/src/filters/fs.rs#L187)

Proposal
--------

It would be  better using same error handling mechanism as finch, (see https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/EndpointResult.scala#L111-L128). Which means:

1) Using separate enum variant which indicates that current filter's branch isn't matched.
2) Fail fast, no error composition, trying next branch only if first returns `NotMatched`
3) An error keeps inside another enum variant

`Reject` and `Rejection` may be changed to:

```rust

pub enum Rejection {
  // signals that current `Filter`'s branch is not valid and cannot be matched.
  NotMatched, 
  // holds an internal error which maybe happens during filter execution or user handler's result
  Err {
    status: StatusCode, 
    err: Box<StdError + Send + 'static>
  }
}

put trait Reject {
  fn status(&self) -> http::StatusCode
  fn into_response(&self) -> ::reply::Response
  fn cause(&self) -> Option<StdError + Send + 'static>
  fn is_matched(&self) -> bool
}

impl Reject for Rejection { ... }
```

**Comment by seanmonstar** [comment] 2018-08-15 18:41
The current rejection system in warp is a lot closer to that of [Akka's rejections](https://doc.akka.io/docs/akka-http/current/routing-dsl/rejections.html), which specifically allows for other routes to be tried even if there is a rejection that isn't equivalent to NotMatched/NotFound.

This allows for things predicates to check for things like query parameters or headers, and if one is wrong, it may wish to tell the user it's a `400 Bad Request`, not `404 Not Found`, while still allowing an alternative route to notice and instead serve a response.

**Comment by dmexe** [comment] 2018-08-15 19:09
Then Rejection signature may be changed to

```rust
struct Rejection {
  reason: Reason,
  err: Box<StdError + Send + 'static>
}
```

it still able to combine status codes, and also contains an error message. Combine would be check reason and use an error from the most important instance. eg

```
  Rejection(NOT_FOUND, err1) + Rejection(SERVER_ERROR, err2) => Rejection(NOT_FOUND + SERVER_ERROR, err2)
```

**Comment by stevedonovan** [comment] 2018-09-17 12:54
This is also very much a requirement for us - I note that `Rejection` has a `with` method where the rejection can be given a boxed error. But alas, does not actually get put into the body.

Of course, one can by-pass `Rejection` and return `Reply` using `Response::Builder`. But then the problem is that there are potentially two types being returned matching a `impl Reply`. In Hyper there is at least Either, and I can't box that Reply...

**Comment by stevedonovan** [comment] 2018-09-17 14:28
The workaround I stumbled on, was that after using `with`, the `Rejection` could be serialized out to JSON in a `recover()` handler. Not too shabby...

**Comment by dmexe** [comment] 2018-09-17 17:05
@stevedonovan see #94, 

I've improved an error handling for custom errors, you could turn a Rejection into JSON response without boilerplate code.

**Comment by stevedonovan** [comment] 2018-09-18 05:55
That feels like a very good extension to Rejection, thanks! Looking forward to the merge. In this case, I'm generating warp boilerplate automatically anyway, so it was not too awkward, but this is definitely an ergonomic improvement.

**Comment by seanmonstar** [comment] 2018-10-03 21:42
The improvements in #94 are part of 0.1.5, so I'm going to close this up.

**Closed by seanmonstar** 2018-10-03 21:42 UTC
Labels: rfc

**Comment by ZakisM** [comment] 2020-01-31 11:24
Is this still possible to do with the latest version of Warp (0.2.1), if so could you please update the error/rejection examples? I am trying to return the exact reason for the error in JSON format, however I can't access the  "reason" field from "Rejection".

**Comment by danstewart** [comment] 2020-06-20 17:54
@ZakisM You can just call `.to_string()` on the cause, like this

```
if let Some(e) = err.find::<warp::filters::body::BodyDeserializeError>() {
	code = http::StatusCode::BAD_REQUEST;
	message = e.to_string();
}
```
