### ISSUE TITLE
multipart: crate or module and rls.

### ISSUE THREAD

**Issue by cheako** [seanmonstar/warp#424] opened 2020-01-28 03:31 UTC
Turns out trying to get rls to understand that multipart is a create and not a module is impossible.  I found this out when trying to write streaming_multipart.  I don't know if I can make use of the multipart crate, because I'm unable to query it VIA rls.

Consider renaming modules that share the same names as crates, Thanks.

**Comment by seanmonstar** [comment] 2020-01-28 03:43
I don't know what you mean. What's the code and error look like?

**Comment by cheako** [comment] 2020-01-28 06:49
The error is that tool tips and goto links direct to the module always and never the create.

**Comment by seanmonstar** [comment] 2020-01-28 16:32
I'm sorry, I'd like to help, but I need more information to be able to do so. I can't see your screen.

Did you do something like `use warp::*` or `use warp::multipart`, and that is shadowing the `multipart` crate? Or something else?

**Comment by cheako** [comment] 2020-01-28 19:14
I don't know if I could explain.  I created a new module streaming_multipart.rs.  I just triple checked it's nothing simple like one use case shadowing another.  What I did was copy multipart.rs and then the ```use multipart::server::Multipart;``` wasn't resolvable.  I prefied it with ```::``` and this didn't change anything.

**Comment by seanmonstar** [comment] 2020-01-29 21:43
Sounds like a general Rust question, closing as not a bug in warp.

**Closed by seanmonstar** 2020-01-29 21:43 UTC
